# Generated by Django 4.2 on 2023-04-17 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='place',
            field=models.CharField(max_length=225),
        ),
    ]
